apiVersion: apps/v1
kind: Deployment
metadata:
  name: loyalty-event-service
  labels:
    app: loyalty-event-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loyalty-event-service
  template:
    metadata:
      labels:
        app: loyalty-event-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: loyalty-event-service
        image: loyalty-event-service:1.0-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 9080
        envFrom:
        - secretRef:
            name: loyalty-db-secret
        - secretRef:
            name: loyalty-oidc-secret
        env:
        - name: WLP_LOGGING_CONSOLE_LOGLEVEL
          value: INFO
---
apiVersion: v1
kind: Service
metadata:
  name: loyalty-event-service
  labels:
    app: loyalty-event-service
spec:
  ports:
  - port: 9080
    targetPort: 9080
  selector:
    app: loyalty-event-service
---
apiVersion: v1
kind: Route
metadata:
  name: loyalty-event-service
spec:
  to:
    kind: Service
    name: loyalty-event-service

